### PR TITLE
Upgrade to gtkd 3.0.0 to be able use dmd 2.067

### PR DESCRIPTION
**Pull request by NCrashed**
Package cannot be built with gtkd `2.4.2` (warnings and errors), but with `3.0.0` version everything is OK.

### CODE REVIEW

**Comment by dnadlinger** [comment]
Thanks!

**Comment by NCrashed** [comment]
Thanks! Could you make new release tag to be able to use fixed version within dub?

**Comment by dnadlinger** [comment]
Sure, give me a second.

**Comment by dnadlinger** [comment]
Done. I added a further little tweak to avoid unused dependencies (gets rid of a build problem at least on Linux x86_64/2.066).

**Comment by NCrashed** [comment]
Thanks. The library is very helpful although have a little docs.

P.S. Gone away to disturb maintainers of another packages that haven't been ported to new version.

**Comment by dnadlinger** [comment]
Yeah, doc improvements would definitely be useful. Don't expect too much from my side, though, I just needed to use David's original work in a quick one-off project that uses Dub.

**Comment by NCrashed** [comment]
So I don't expect anything, I quite comfortable to inspect sources when docs aren't available.

**Pull request merged**
